### ISSUE TITLE
target_link_directories is not available in cmake 3.5

### ISSUE THREAD

**Issue by azeey** [ros2/console_bridge_vendor#23]
The minimum required cmake version in the CMakeLists.txt file is 3.5, but here
https://github.com/ros2/console_bridge_vendor/blob/02f62e8b0d241e8fad2b5908a72ccb167a33c6d9/CMakeLists.txt#L114

`target_link_directories` is used, which was added in [cmake 3.13](https://cmake.org/cmake/help/latest/release/3.13.html#id9). This makes this package fail to build on Ubuntu Bionic.

**Comment by clalancette** [comment]
Hm, good call.  If I comment out that line, I can still compile and run locally.  It looks like this was added in https://github.com/ros2/console_bridge_vendor/pull/21 ; @ahcorde can you provide some more background on why this was needed?

**Comment by ahcorde** [comment]
I proposed a solution https://github.com/ros2/console_bridge_vendor/pull/25

**Comment by azeey** [comment]
Closed by #25
