### ISSUE TITLE
upgrade to v.0.4.3

### ISSUE THREAD

**Issue by Karsten1987** [ros2/console_bridge_vendor#5]
I recently ran into https://github.com/ros2/ros2/issues/743 which essentially led to https://github.com/ros/console_bridge/pull/63

This is more like a question, wondering why we are settled on v.0.4.1 instead of master (v.0.4.3).

**Comment by clalancette** [comment]
Since we've moved very far forward since this issue was opened, I don't think it is relevant anymore.  I'm going to close it out, but feel free to reopen if there is something we need to do there.
